apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: todoapp
spec:
  containers:
    - name: busybox
      image: ikulyk404/busyboxplus:curl
      imagePullPolicy: Always
      command: ["sh", "-c", "while true; do sleep 30; done"]

      livenessProbe:
        exec:
          command: ["sh", "-c", "echo alive"]
        initialDelaySeconds: 10
        periodSeconds: 20
  restartPolicy: Always
